### PR TITLE
Added black scheme

### PR DESCRIPTION
**Pull request by ghost**
I added a new black on white color scheme.

### CODE REVIEW

**Comment by tonylegrone** [comment]
Hey, I'm very sorry. I just saw this pull request for the first time yesterday. I never get any notifications so I completely missed this one.

I'd love to merge this in, but you've deleted your fork of it and I can't figure out how to get the diff from github. If you still have your copy locally, I'll merge it if you restore your github project for me.

Thanks!

**Comment by ghost** [comment]
Sorry, I just deleted the fork a week ago.
Is it not possible to merge this pull request without the fork?

If you can't merge it, I will try this to restore the fork: http://stackoverflow.com/questions/20977530/recover-a-commit-sent-as-a-pull-request-from-a-deleted-fork-on-github

**Comment by tonylegrone** [comment]
Github won't let me merge the pull request because the source is gone now. But I actually just figured out how to get the link to the raw patch and was able to apply it with your original timestamp and you as the author. I'll get it updated on the package control in a few minutes.

**Comment by tonylegrone** [comment]
It updated automatically when I pushed up the new tag. Thanks for adding to my little theme! Again, sorry I didn't see this for so long. I feel terrible.

**Comment by ghost** [comment]
No problem. Thanks for merging this!

**Comment by tonylegrone** [comment]
I failed to push with `--tags` yesterday, so the package control hasn't seen it yet. I just fixed that problem so it should roll out soon.

**Pull request closed without merging**
